name: Deploy to GitHub Pages Branch

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push to gh-pages branch
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper versioning

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          echo "Installed dependencies using Yarn"

      - name: Build
        run: |
          echo "Starting build process..."
          yarn build
          echo "🚀 Build completed successfully"

      - name: Copy CNAME file to dist
        run: |
          if [ -f "public/CNAME" ]; then
            cp public/CNAME dist/
            echo "CNAME file copied to dist directory"
          fi

      - name: Deploy to GitHub Pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
          commit-message: "Deploy website [skip ci]"
